/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Typed Anchor wrapper for the relief-ledger program.
 * Used server-side only (API routes). Not imported by client components.
 */

import { Program, AnchorProvider, web3 } from "@coral-xyz/anchor";
import { getConnection, getBackendKeypair } from "./solana";
import { isMockChain, mockIssueVoucher, mockRedeemVoucher, explorerUrl } from "./mock-chain";
import { createHash } from "crypto";

let IDL: any = null;

async function getIDL() {
  if (IDL) return IDL;
  try {
    // Generated by `anchor build` — not present until the Anchor program is compiled.
    // Using a runtime eval-require so webpack doesn't try to bundle the missing file.
    const idlPath = process.cwd() + "/programs/relief-ledger/target/idl/relief_ledger.json";
    IDL = JSON.parse((await import("fs")).readFileSync(idlPath, "utf8"));
  } catch {
    IDL = null;
  }
  return IDL;
}

export function sha256(input: string): Buffer {
  return createHash("sha256").update(input).digest();
}

function makeProvider(connection: web3.Connection, keypair: web3.Keypair): AnchorProvider {
  const wallet = {
    publicKey: keypair.publicKey,
    signTransaction: async (tx: web3.Transaction) => { tx.partialSign(keypair); return tx; },
    signAllTransactions: async (txs: web3.Transaction[]) => { txs.forEach(tx => tx.partialSign(keypair)); return txs; },
  };
  return new AnchorProvider(connection, wallet as any, { commitment: "confirmed" });
}

export async function issueVoucherOnChain(params: {
  voucherId: string;
  orgId: string;
  category: string;
  valueCents: number;
  unitCount: number;
}): Promise<{ signature: string; explorerUrl: string }> {
  if (isMockChain()) {
    return mockIssueVoucher({
      voucherId: params.voucherId,
      orgId: params.orgId,
      category: 0,
      valueCents: params.valueCents,
      unitCount: params.unitCount,
    });
  }

  const idl = await getIDL();
  if (!idl) throw new Error("IDL not compiled yet. Run `anchor build` first.");

  const keypair = getBackendKeypair();
  const connection = getConnection();
  const provider = makeProvider(connection, keypair);
  const program = new Program(idl, provider);

  const voucherIdHash = sha256(params.voucherId);
  const orgIdHash = sha256(params.orgId);
  const categoryCode = ({ meals: 0, hygiene: 1, transit: 2, laundry: 3 } as Record<string, number>)[params.category] ?? 0;

  const [voucherPDA] = web3.PublicKey.findProgramAddressSync(
    [Buffer.from("voucher"), voucherIdHash],
    program.programId
  );

  const sig = await (program.methods as any)
    .issueVoucher(
      Array.from(voucherIdHash),
      Array.from(orgIdHash),
      categoryCode,
      params.valueCents,
      params.unitCount
    )
    .accounts({
      voucherAccount: voucherPDA,
      authority: keypair.publicKey,
      systemProgram: web3.SystemProgram.programId,
    })
    .signers([keypair])
    .rpc();

  return { signature: sig, explorerUrl: explorerUrl(sig) };
}

export async function redeemVoucherOnChain(params: {
  voucherId: string;
  vendorId: string;
}): Promise<{ signature: string; explorerUrl: string }> {
  if (isMockChain()) {
    return mockRedeemVoucher({
      voucherId: params.voucherId,
      vendorId: params.vendorId,
    });
  }

  const idl = await getIDL();
  if (!idl) throw new Error("IDL not compiled yet. Run `anchor build` first.");

  const keypair = getBackendKeypair();
  const connection = getConnection();
  const provider = makeProvider(connection, keypair);
  const program = new Program(idl, provider);

  const voucherIdHash = sha256(params.voucherId);
  const vendorHash = sha256(params.vendorId);

  const [voucherPDA] = web3.PublicKey.findProgramAddressSync(
    [Buffer.from("voucher"), voucherIdHash],
    program.programId
  );

  const sig = await (program.methods as any)
    .redeemVoucher(
      Array.from(voucherIdHash),
      Array.from(vendorHash)
    )
    .accounts({
      voucherAccount: voucherPDA,
      authority: keypair.publicKey,
    })
    .signers([keypair])
    .rpc();

  return { signature: sig, explorerUrl: explorerUrl(sig) };
}
